name: capillary-flow
channels:
  - defaults
dependencies:
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.9.24=py39haa95532_0
  - openssl=1.1.1s=h2bbff1b_0
  - pip=22.2.2=py39haa95532_0
  - python=3.9.13=h6244533_2
  - setuptools=65.5.0=py39haa95532_0
  - sqlite=3.39.3=h2bbff1b_0
  - tzdata=2022f=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py39haa95532_2
  - pip:
    - astropy==5.1.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - fonttools==4.38.0
    - imageio==2.22.3
    - kiwisolver==1.4.4
    - matplotlib==3.6.2
    - networkx==2.8.8
    - numpy==1.23.4
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.5.1
    - patsy==0.5.3
    - pillow==9.3.0
    - pyerfa==2.0.0.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pywavelets==1.4.1
    - pyyaml==6.0
    - scikit-image==0.19.3
    - scipy==1.9.3
    - six==1.16.0
    - statsmodels==0.13.5
    - tifffile==2022.10.10
